// Mock market data – replace with real API calls via SWR hooks
export const INDICES = [
    {
        symbol: "NIFTY50",
        name: "NIFTY 50",
        price: 22458.35,
        change: -123.45,
        changePct: -0.55,
        high: 22601.2,
        low: 22389.8,
        currency: "INR",
        market: "NSE",
    },
    {
        symbol: "SENSEX",
        name: "BSE SENSEX",
        price: 73847.15,
        change: -387.2,
        changePct: -0.52,
        high: 74254.9,
        low: 73720.6,
        currency: "INR",
        market: "BSE",
    },
    {
        symbol: "BANKNIFTY",
        name: "BANK NIFTY",
        price: 47892.6,
        change: 234.8,
        changePct: 0.49,
        high: 48120.5,
        low: 47612.3,
        currency: "INR",
        market: "NSE",
    },
    {
        symbol: "BTC",
        name: "Bitcoin",
        price: 67842.5,
        change: 1284.3,
        changePct: 1.93,
        high: 68450.0,
        low: 66200.0,
        currency: "USD",
        market: "CRYPTO",
    },
    {
        symbol: "ETH",
        name: "Ethereum",
        price: 3521.4,
        change: -87.6,
        changePct: -2.43,
        high: 3640.0,
        low: 3480.0,
        currency: "USD",
        market: "CRYPTO",
    },
];

export const WATCHLIST_STOCKS = [
    { symbol: "RELIANCE", name: "Reliance Industries", price: 2847.3, changePct: 0.82, exchange: "NSE" },
    { symbol: "TCS", name: "Tata Consultancy Services", price: 3892.15, changePct: -0.34, exchange: "NSE" },
    { symbol: "INFY", name: "Infosys", price: 1654.8, changePct: 1.12, exchange: "NSE" },
    { symbol: "HDFC", name: "HDFC Bank", price: 1612.45, changePct: -0.67, exchange: "NSE" },
    { symbol: "ICICIBANK", name: "ICICI Bank", price: 1089.7, changePct: 0.45, exchange: "NSE" },
    { symbol: "WIPRO", name: "Wipro", price: 523.6, changePct: -1.23, exchange: "NSE" },
    { symbol: "HCLTECH", name: "HCL Technologies", price: 1487.25, changePct: 0.76, exchange: "NSE" },
    { symbol: "BHARTIARTL", name: "Bharti Airtel", price: 1267.9, changePct: 1.45, exchange: "NSE" },
];

export const CRYPTO_DATA = [
    { symbol: "BTC", name: "Bitcoin", price: 67842.5, changePct: 1.93, volume: "42.8B", marketCap: "1.33T", fundingRate: 0.01 },
    { symbol: "ETH", name: "Ethereum", price: 3521.4, changePct: -2.43, volume: "18.2B", marketCap: "423.5B", fundingRate: -0.005 },
    { symbol: "SOL", name: "Solana", price: 178.34, changePct: 3.71, volume: "5.4B", marketCap: "84.2B", fundingRate: 0.015 },
    { symbol: "XRP", name: "Ripple", price: 0.612, changePct: -0.87, volume: "2.1B", marketCap: "34.8B", fundingRate: 0.002 },
    { symbol: "BNB", name: "BNB", price: 412.8, changePct: 0.54, volume: "1.8B", marketCap: "61.4B", fundingRate: 0.008 },
    { symbol: "DOGE", name: "Dogecoin", price: 0.182, changePct: -1.34, volume: "1.2B", marketCap: "26.1B", fundingRate: 0.003 },
    { symbol: "ADA", name: "Cardano", price: 0.594, changePct: 2.14, volume: "0.8B", marketCap: "21.2B", fundingRate: 0.006 },
    { symbol: "AVAX", name: "Avalanche", price: 41.73, changePct: -3.21, volume: "0.6B", marketCap: "17.1B", fundingRate: -0.002 },
];

export const PREDICTIONS = [
    {
        id: 1,
        question: "Will NIFTY close above 23,000 this week?",
        yesProb: 34,
        volume: "₹12.4Cr",
        category: "India Markets",
        trending: false,
    },
    {
        id: 2,
        question: "Will BTC hit $70,000 this month?",
        yesProb: 58,
        volume: "$8.7M",
        category: "Crypto",
        trending: true,
    },
    {
        id: 3,
        question: "Will RBI cut rates in the next meeting?",
        yesProb: 72,
        volume: "₹34.2Cr",
        category: "Macro",
        trending: true,
    },
    {
        id: 4,
        question: "Will Reliance Industries beat Q3 earnings?",
        yesProb: 61,
        volume: "₹6.8Cr",
        category: "Earnings",
        trending: false,
    },
];

export const HEATMAP_DATA = [
    { symbol: "RELIANCE", sector: "Energy", changePct: 0.82, marketCap: "19.2T", volume: "8.4M", pe: 28.4 },
    { symbol: "TCS", sector: "IT", changePct: -0.34, marketCap: "14.1T", volume: "2.1M", pe: 32.1 },
    { symbol: "HDFC", sector: "Banking", changePct: -0.67, marketCap: "12.8T", volume: "5.6M", pe: 19.2 },
    { symbol: "ICICIBANK", sector: "Banking", changePct: 0.45, marketCap: "7.6T", volume: "7.2M", pe: 18.7 },
    { symbol: "INFY", sector: "IT", changePct: 1.12, marketCap: "7.0T", volume: "3.4M", pe: 27.3 },
    { symbol: "SBIN", sector: "Banking", changePct: -1.45, marketCap: "6.8T", volume: "12.1M", pe: 11.2 },
    { symbol: "BHARTIARTL", sector: "Telecom", changePct: 1.45, marketCap: "6.7T", volume: "4.8M", pe: 45.6 },
    { symbol: "BAJFINANCE", sector: "Finance", changePct: -2.18, marketCap: "4.8T", volume: "1.9M", pe: 31.8 },
    { symbol: "HCLTECH", sector: "IT", changePct: 0.76, marketCap: "4.0T", volume: "2.6M", pe: 24.5 },
    { symbol: "WIPRO", sector: "IT", changePct: -1.23, marketCap: "2.8T", volume: "5.2M", pe: 22.1 },
    { symbol: "ASIANPAINT", sector: "Consumer", changePct: 0.34, marketCap: "2.6T", volume: "1.2M", pe: 52.3 },
    { symbol: "MARUTI", sector: "Auto", changePct: 1.87, marketCap: "3.2T", volume: "0.8M", pe: 29.4 },
    { symbol: "TATAMOTORS", sector: "Auto", changePct: -0.92, marketCap: "2.1T", volume: "6.7M", pe: 8.4 },
    { symbol: "AXISBANK", sector: "Banking", changePct: 0.28, marketCap: "3.4T", volume: "4.3M", pe: 15.6 },
    { symbol: "LT", sector: "Infra", changePct: -0.54, marketCap: "4.9T", volume: "1.4M", pe: 34.2 },
    { symbol: "SUNPHARMA", sector: "Pharma", changePct: 2.31, marketCap: "3.9T", volume: "2.1M", pe: 38.7 },
    { symbol: "NTPC", sector: "Energy", changePct: 0.67, marketCap: "3.6T", volume: "8.9M", pe: 17.3 },
    { symbol: "POWERGRID", sector: "Energy", changePct: -0.45, marketCap: "2.4T", volume: "4.5M", pe: 18.9 },
    { symbol: "KOTAKBANK", sector: "Banking", changePct: 1.12, marketCap: "3.7T", volume: "3.1M", pe: 22.4 },
    { symbol: "HINDUNILVR", sector: "Consumer", changePct: -0.78, marketCap: "5.8T", volume: "1.8M", pe: 61.2 },
];

export const NEWS_ITEMS = [
    {
        id: 1,
        headline: "RBI holds rates steady; Governor signals potential cut in Q2 2025",
        source: "Economic Times",
        time: "2h ago",
        category: "Macro",
        sentiment: "neutral",
    },
    {
        id: 2,
        headline: "Reliance Industries Q3 results: Net profit up 18% YoY, beats estimates",
        source: "Bloomberg India",
        time: "3h ago",
        category: "Earnings",
        sentiment: "positive",
    },
    {
        id: 3,
        headline: "Bitcoin surges past $68K as ETF inflows hit record $1.2B in a single day",
        source: "CoinDesk",
        time: "4h ago",
        category: "Crypto",
        sentiment: "positive",
    },
    {
        id: 4,
        headline: "IT sector under pressure as US macro data triggers global risk-off sentiment",
        source: "Mint",
        time: "5h ago",
        category: "Markets",
        sentiment: "negative",
    },
    {
        id: 5,
        headline: "Sensex falls 400 points on weak global cues; Bank Nifty outperforms",
        source: "NDTV Profit",
        time: "6h ago",
        category: "Markets",
        sentiment: "negative",
    },
];
